version: '3.7'
services:
    ecomdb:
        image: postgres:alpine
        container_name: ecomdb
        restart: always
        env_file:
            - db.env
        ports:
            - "5432:5432"
        volumes:
            - ./db_data:/var/lib/postgresql/data
    ecom-redis:
        image: redis:alpine
        container_name: ecom-redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./redis_data:/data
