version: '3.7'
services:
    ecomdb:
        image: postgres:alpine
        container_name: ecomdb
        restart: always
        env_file:
            - db.env
        ports:
            - "5432:5432"
        volumes:
            - ./db_data:/var/lib/postgresql/data
